title: Climate change and enviroment
author: pascualbeatriz
email: pascualbeatriz@domain.com
description: > # this means to ignore newlines until "baseurl:"
We are hearing it more and more: the climate is changing. But what does it mean? The climate is seen as the normal weather in a specific area. For example, the temperatures in the Amazon are always high and it is raining almost every day, while on the Antarctic it is always freezing and almost no rain falls. When the normal temperature and the amount of rain in a specific area changes, there is a transition in the normal weather. This is climate change. Not only in specific areas climate change is observed, all over the world the consequences of climate change are felt.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  pascualbeatriz # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
